const appRoutes = [
  {
    path: "/",
    component: () => import("@/layouts/AppLayout.vue"),
    meta: { requiresAuth: true }, // 🔥 NEED TO LOGIN
    children: [
      {
        path: "",
        name: "Home",
        component: () => import("@/views/app/HomeView.vue"),
        meta: {
          roles: [
            "admin",
            "direktur",
            "konsolidator",
            "pkrt",
            "pklnprt",
            "pkp",
            "pmtb",
            "pi",
            "xm",
            "lapres",
            "dnpeng",
          ],
        },
      },
      {
        path: "insight/:category",
        name: "Insight",
        component: () => import("@/views/app/InsightView.vue"),
        meta: {
          roles: [
            "admin",
            "direktur",
            "konsolidator",
            "pkrt",
            "pklnprt",
            "pkp",
            "pmtb",
            "pi",
            "xm",
            "lapres",
            "dnpeng",
          ],
        },
      },
      {
        path: "data",
        name: "Data",
        component: () => import("@/views/app/DataView.vue"),
        meta: {
          roles: [
            "admin",
            "direktur",
            "konsolidator",
            "pkrt",
            "pklnprt",
            "pkp",
            "pmtb",
            "pi",
            "xm",
          ],
        },
      },
      {
        path: "dashboard",
        name: "Dashboard",
        component: () => import("@/views/app/DashboardView.vue"),
        meta: {
          roles: [
            "admin",
            "direktur",
            "konsolidator",
            "pkrt",
            "pklnprt",
            "pkp",
            "pmtb",
            "pi",
            "xm",
          ],
        },
      },
      {
        path: "kompilasi/:pdb",
        name: "Kompilasi",
        component: () => import("@/views/app/KompilasiView.vue"),
        meta: {
          roles: [
            "admin",
            "direktur",
            "konsolidator",
            "pkrt",
            "pklnprt",
            "pkp",
            "pmtb",
            "pi",
            "xm",
            "lapres",
          ],
        },
      },
      {
        path: "suplemen",
        name: "Suplemen",
        component: () => import("@/views/app/SuplemenView.vue"),
        meta: {
          roles: [
            "admin",
            "direktur",
            "konsolidator",
            "pkrt",
            "pklnprt",
            "pkp",
            "pmtb",
            "pi",
            "xm",
            "lapres",
            "dnpeng",
          ],
        },
      },
      {
        path: "materi/:category",
        name: "Materi",
        component: () => import("@/views/app/MateriView.vue"),
        meta: {
          roles: [
            "admin",
            "direktur",
            "konsolidator",
            "pkrt",
            "pklnprt",
            "pkp",
            "pmtb",
            "pi",
            "xm",
            "lapres",
            "dnpeng",
          ],
        },
      },
      {
        path: "upload-file",
        name: "UploadFile",
        component: () => import("@/views/app/UploadFileView.vue"),
        meta: {
          roles: ["admin"],
        },
      },
      {
        path: "upload-monitoring",
        name: "UploadMonitoring",
        component: () => import("@/views/app/UploadMonitoringView.vue"),
        meta: {
          roles: ["admin"],
        },
      },
      {
        path: "register",
        name: "Register",
        component: () => import("@/views/auth/RegisterView.vue"),
        meta: {
          roles: ["admin"],
        },
      },
      {
        path: "monitoring",
        name: "Monitoring",
        component: () => import("@/views/app/MonitoringView.vue"),
        meta: {
          roles: [
            "admin",
            "direktur",
            "konsolidator",
            "pkrt",
            "pklnprt",
            "pkp",
            "pmtb",
            "pi",
            "xm",
            "lapres",
            "dnpeng",
          ],
        },
      },
    ],
  },
];

export default appRoutes;
